### PR TITLE
Add webpack rebuild via Dockerfile

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/161)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/161)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.  I'm interested both in feedback on the idea itself, as well as the implementation.

**Review by jwnimmer-tri — COMMENTED** [review]
+@sammy-tri for platform review per schedule, please.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/161#-:-NoMu5B72gIHY-_TOoOx:b-1krawd)* status: all files reviewed, 1 unresolved discussion (waiting on @sammy-tri and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/meshcat-dev/meshcat/161#-NoIZIf_1HTZiK49dgDW:-NoMtqfL4gW4PRr3m2Q_:byg4z34) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Per our f2f -- it would be nice if `rebuild.sh` provided guidance in the face of missing docker or buildx.
</blockquote></details>

I didn't like any of the "detect and advise bash code" I tried.  Instead, I opted for a better Readme.

___

**Review by SeanCurtis-TRI — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/161)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @sammy-tri)

**Review by sammy-tri — APPROVED** [review]
:lgtm:  Seemed to work locally though I didn't attempt to run the output.

> Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/161#-:-NoSgNkW1nSlfAdomWrK:b-pwwfi1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — APPROVED** [review]
In my review, ran it with `index.js` unmodified and modified. Unmodified, there were no diffs. Modified, there was a detected change. So, I'm content that it does what it says it does.

> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/161#-:-NoSiz4X-qRhMFRlAvmO:bnqxf2k)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Yup.  My only concern is whether @sammy-tri also saw unmodified => no diffs.

(I'm not worried about the modified => diffs side of things; that seems sufficiently proven already.)

**Review by sammy-tri — APPROVED** [review]
Yes, it appears to generate identical files in `dist`/

> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/161#-:-NoTNT-M4fpFGAVr850z:b-e0lky3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Tyvm!

**Pull request merged**
