### PR TITLE
Start to backfill some protocol documentation

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
[See here for a rendered preview](https://github.com/jwnimmer-tri/meshcat/blob/readme/Readme.md).

- - -
This change is [Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/166)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI could I ask for any early feature-review feedback here?  I still have some TODOs to fill out, but I should probably check if I'm moving in the right direction.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I think this is good. I do somewhat bemoan the informality. There's a part of me wondering if some kind of grammar definition wouldn't be helpful. Especially for the complex `set_object()`. But this is a definite improvement.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/166#-:-NoshExBEmgguwQS0FzY:b38q3kp)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Thanks.  I'll ping you again once I have the additional JSON examples filled in.  My hope is that will help mitigate the lack of a more structured specification.

**Review by jwnimmer-tri — COMMENTED** [review]
This is ready for a full review no.

No particular rush, I just want to have this baseline ready for when I start _changing_ the protocol (by allowing `url` instead of `data` for assets).

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/166#-:-Np1US_u9Cd3KVa5NG8D:b1s6gg1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
This is ready for a full review now*.

> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/166#-:-Np1Ucr-86m_T--e5o-e:bxrlirb)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/166)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — APPROVED** [review]
:LGTM:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/166#-:-NpL3rjm-X1d_m8yravQ:bmxilld)* status: all files reviewed, 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`test/texture_text.html` line 50 at r3](https://reviewable.io/reviews/meshcat-dev/meshcat/166#-NpL3Cmx2Tryn0FxpwHK:-NpL3Cmx2Tryn0FxpwHL:bee0o5a) ([raw file](https://github.com/meshcat-dev/meshcat/blob/226e298460397cbbcbf7cbd725e3991ecdc73fbc/test/texture_text.html#L50)):*
> ```HTML
>                         transparent: true,
>                         map: "0c8c99a8-bba8-11ee-b7a2-4b79088b524d",
>                     }
> ```

BTW If you change the default sided-ness to "2", you can read the text on both sides. The test, as is, is sufficient to show that the text textures work. Extending it slightly to make the text visible from both sides may serve further pedagogical value.



_Suggestion:_
```HTML
                    {
                        uuid: "6fe7011b-bba7-11ee-b7a2-4b79088b524d",
                        type: "MeshPhongMaterial",
                        transparent: true,
                        map: "0c8c99a8-bba8-11ee-b7a2-4b79088b524d",
                        // Make the text visible front and back (double sided).
                        side: 2,
                    }
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/166)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Pull request merged**
