### PR TITLE
Help with opacity configuration

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Previously, setting the opacity of an object required setting the color of the object. Now, opacity can be set directly. Furthermore, the opacity can be *modulated* so that the material's intrinsic opacity can be scaled by an external factor (e.g., a slider).

The user can now call set_property(path, "opacity", value) or set_property(path, "modulated_opacity", value) to modify the opacity of all of the materials rooted at path. (Note: the "all materials rooted at path" was the previously existing behavior for setting the "color" property. Now it is made more explicit in the code.)

A new test web page has been added in which objects with various configurations can interactively have their opacity modified.

- - -
This change is [Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/153)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
Note to reviewers: Open `opacity.html` in your local browser. There are printed instructions/explanations. Ultimately, play with the sliders and convince yourself it is behaving as you would expect.

**Review by jwnimmer-tri — COMMENTED** [review]
Testing reviewable publish.

> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-:-NdgX9aA1TgKYGLUSdkC:b-b3lpyg)* status: 0 of 3 files reviewed, all discussions resolved

**Review by zachfang — COMMENTED** [review]
+zachfang for feature review. (Couldn't do that via the GitHub page.)

> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-:-NdgxNJJCUrDx8GN9hpY:b-x19b6p)* status: 0 of 3 files reviewed, all discussions resolved

**Review by zachfang — COMMENTED** [review]
:lgtm_strong: with two questions.

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-:-NdhOT6uAq4RqoGpeb4m:b-5srihw)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[`test/opacity.html` line 17 at r1](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-NdhN3bFENYWX_9i-D1T:-NdhN3bFENYWX_9i-D1U:b-blfbrw) ([raw file](https://github.com/meshcat-dev/meshcat/blob/0e30a85f5a9763ecd75a6c87bc094b45b159d8c4/test/opacity.html#L17)):*
> ```HTML
>             <li>Green, opaque, double-sided (move the camera inside, and you
>                 will still see its green faces).</li>
>             <li>Red, transparent, double-sided (you can see back faces through
> ```

BTW/question. Intuitively, I would think `{single, double}-sided` means whether both sides of a face are colored. Why this has to do with transparency? For the four combinations, only the red tetrahedron is actually transparent?



_Code quote:_
```HTML
transparent, double-sided
```
___
*[`test/opacity.html` line 21 at r1](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-NdhO77sCDqCPcWx10kd:-NdhO77t1YiFzlNka8oE:b71tk6g) ([raw file](https://github.com/meshcat-dev/meshcat/blob/0e30a85f5a9763ecd75a6c87bc094b45b159d8c4/test/opacity.html#L21)):*
> ```HTML
>             <li>Yellow, transparent, single-sided (no faces are visible through
>                 the transparent front faces).</li>
>             <li>Purple, opaque, single-sided box (you can look through the walls
> ```

BTW/question. This is another part I don't fully understand. If the box is opaque, why we can see through it?



_Code quote:_
```HTML
Purple, opaque, single-sided box
```

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm: after running test locally, small BTW question on embedded assets

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-:-Ndkar8R-_W_tYS4S9mN:bggnpxo)* status: all files reviewed, 1 unresolved discussion (waiting on @SeanCurtis-TRI)

___
*[`test/opacity.html` line 52 at r1](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-NdkafAiAQjrj07AIkWC:-NdkafAiAQjrj07AIkWD:b-eah5z1) ([raw file](https://github.com/meshcat-dev/meshcat/blob/0e30a85f5a9763ecd75a6c87bc094b45b159d8c4/test/opacity.html#L52)):*
> ```HTML
>             var viewer = new MeshCat.Viewer(document.getElementById("meshcat-pane"));
> 
>             let gltf_pyramids = `{"asset":{"generator":"Khronos glTF Blender I/O v3.6.27","version":"2.0"},"scene":0,"scenes":[{"name":"Scene","nodes":[0,1,2,3]}],"nodes":[{"mesh":0,"name":"OpaqueDoubleTet","translation":[0,0,0]},{"mesh":1,"name":"TransparentDoubleTet","translation":[2,0,0]},{"mesh":2,"name":"OpaqueSingleTet","translation":[-2,0,0]},{"mesh":3,"name":"TransparentSingleTet","translation":[0,2,0]}],"materials":[{"doubleSided":true,"name":"OpaqueDoubleMMat","pbrMetallicRoughness":{"baseColorFactor":[0,1,0,1]}},{"alphaMode":"BLEND","doubleSided":true,"name":"TransparentDoubleMat","pbrMetallicRoughness":{"baseColorFactor":[1,0,0,0.5]}},{"doubleSided":false,"name":"OpaqueSingleMat","pbrMetallicRoughness":{"baseColorFactor":[0,0,1,1]}},{"alphaMode":"BLEND","doubleSided":false,"name":"TransparentSingleMat","pbrMetallicRoughness":{"baseColorFactor":[1,1,0,0.5]}}],"meshes":[{"name":"OpaqueDoubleMesh","primitives":[{"attributes":{"POSITION":0,"NORMAL":1},"indices":2,"material":0}]},{"name":"TransparentDoubleMesh","primitives":[{"attributes":{"POSITION":0,"NORMAL":1},"indices":2,"material":1}]},{"name":"OpaqueSingleMesh","primitives":[{"attributes":{"POSITION":0,"NORMAL":1},"indices":2,"material":2}]},{"name":"TransparentSingleMesh","primitives":[{"attributes":{"POSITION":0,"NORMAL":1},"indices":2,"material":3}]}],"accessors":[{"bufferView":0,"componentType":5126,"count":12,"max":[1.1620713472366333,1,1.11544668674469],"min":[-0.6132463216781616,-1,-1.11544668674469],"type":"VEC3"},{"bufferView":1,"componentType":5126,"count":12,"type":"VEC3"},{"bufferView":2,"componentType":5123,"count":12,"type":"SCALAR"}],"bufferViews":[{"buffer":0,"byteLength":144,"byteOffset":0,"target":34962},{"buffer":0,"byteLength":144,"byteOffset":144,"target":34962},{"buffer":0,"byteLength":24,"byteOffset":288,"target":34963}],"buffers":[{"byteLength":312,"uri":"data:application/octet-stream;base64,AAAAAAAAgD8AAACAAAAAAAAAgD8AAACAAAAAAAAAgD8AAACAwb6UPwAAgL8AAACAwb6UPwAAgL8AAACAwb6UPwAAgL8AAACAtv0cvwAAgL/1xo6/tv0cvwAAgL/1xo6/tv0cvwAAgL/1xo6/tv0cvwAAgL/1xo4/tv0cvwAAgL/1xo4/tv0cvwAAgL/1xo4/CsB0v4Mclj4AAACAAcdlPbFq9j7W8F+/AcdlPbFq9j7W8F8/AAAAAAAAgL8AAACAo+ODPcASAT+/dly/o+ODPcASAT+/dlw/CsB0v4Mclj4AAACAAAAAAAAAgL8AAACApUhqPXob+D6QdF+/CsB0v4Mclj4AAACAAAAAAAAAgL8AAACApUhqPXob+D6QdF8/BQACAAsACQAAAAYABwADAAoACAABAAQA"}]}`;
> ```

BTW Is it worth briefly documenting how this was generated? e.g.
```
// Scene created using Blender, saved to file, and ...
```

**Comment by jwnimmer-tri** [comment]
The top-level README documents how all of the features work.  When we're adding new features, we should document their API/semantics there as well.

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/153)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[`test/opacity.html` line 17 at r1](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-NdhN3bFENYWX_9i-D1T:-NdkcXoP-EwAFKCP3_1p:bft6v1m) ([raw file](https://github.com/meshcat-dev/meshcat/blob/0e30a85f5a9763ecd75a6c87bc094b45b159d8c4/test/opacity.html#L17)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

> For the four combinations, only the red tetrahedron is actually transparent?

I need you to be extra double sure that the yellow tet is not transparent. It should be. Make sure you turn the camera to look through the yellow tet to see one of the other tets. If you don't see it as transparent, then I'll have to delve into why the disparity between what I see and what you see. When I rotate the camera to look down from above, I see this:



Now, assuming it really is transparent (and is just less obviously so because it isn't rendering the back faces), the *reason* for having tets that are single-sided and double-sided (with the other transparent permutations) is because solving this problem took a number of iterations. In every previous approach for handling opacity I tried (prior to that in this PR), there was *some* combination of sided-ness and initial transparency that wasn't treated well. So, including all of them represents a regression test.
</blockquote></details>

I think your comment below answered this question too. During my testing, I confirmed the yellow tet is transparent when the camera view is outside. I was expecting to see the yellow color too when the camera view is inside as I naively thought that's the behavior for "transparency".
___
*[`test/opacity.html` line 21 at r1](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-NdhO77sCDqCPcWx10kd:-NdkcKxPCx91a874xHxt:b-jhyyta) ([raw file](https://github.com/meshcat-dev/meshcat/blob/0e30a85f5a9763ecd75a6c87bc094b45b159d8c4/test/opacity.html#L21)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

That's the sided-ness. Every triangle has a "front" side and "back" side defined by how the normal is defined (the front side is the side the normal points out of). Single-sided materials only render the front side. So, this purple box has its normals pointing in toward the tetrahedra. So, when I look from the outside, I can't see the wall closest to me, because I'm looking at its back side. But when I look *through* the space, I see the walls on the opposite side of the box pointing back at me.

This is *really* helpful if you're doing a simulation in a room and you want the robot to see the walls, but, in your visualizer, you don't want to be forced to put your camera *inside* the room to see. You can see in from the outside -- like one-way glass.
</blockquote></details>

Got it. Thanks!

**Review by SeanCurtis-TRI — COMMENTED** [review]
README extended.

> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-:-NdkfOxpAGTUnF0RrdSI:b-xsdxi0)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

___
*[`test/opacity.html` line 17 at r1](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-NdhN3bFENYWX_9i-D1T:-NdkfselDE5xyqLSz3nq:b-lpg4pk) ([raw file](https://github.com/meshcat-dev/meshcat/blob/0e30a85f5a9763ecd75a6c87bc094b45b159d8c4/test/opacity.html#L17)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

I think your comment below answered this question too. During my testing, I confirmed the yellow tet is transparent when the camera view is outside. I was expecting to see the yellow color too when the camera view is inside as I naively thought that's the behavior for "transparency".
</blockquote></details>

Nope. The yellow and blue share the property of not seeing it from the inside.  :)
___
*[`test/opacity.html` line 52 at r1](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-NdkafAiAQjrj07AIkWC:-Ndkg26qBP1OP7Zb8bSV:b1uhkxf) ([raw file](https://github.com/meshcat-dev/meshcat/blob/0e30a85f5a9763ecd75a6c87bc094b45b159d8c4/test/opacity.html#L52)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Is it worth briefly documenting how this was generated? e.g.
```
// Scene created using Blender, saved to file, and ...
```
</blockquote></details>

The embedded data thing seems to be a common practice in these files. The nice thing is that its origin is not too important. I could actually take this string, paste it into a file `foo.gltf` and immediately load that file into any glTF viewer. There are other files that have stl, dae, obj files (and I've added files that also include base64-encoded images as background images). None of them are documented as to how they were authored. That includes the ability to create `foo.gltf`, pull it into the editor of your choice (e.g., Blender), edit it, export it again, and drop that text over this text to change the test.

And, finally, in this special case, it's actually self documented as having been created by Blender as part of the json.  :)

**Review by zachfang — COMMENTED** [review]
Some editorial nits with :lgtm:.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-:-NdkqesMDWAAait8q4ee:b-rowfhu)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[`Readme.md` line 308 at r3](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-NdkpY3uCrXgtDtmfyIV:-NdkpY3v3lxsNEaOvpAZ:bo38hjv) ([raw file](https://github.com/meshcat-dev/meshcat/blob/77c5153e8ace0a7f28dce91c8a22ffc3e6a65c2b/Readme.md#L308)):*
> ```Markdown
> This would assign the opacity value 0.5 to *all* of the materials found rooted
> at `"/path/to/my/geometry"`. (That means using the path `"/path"` could affect
> many geometries). However, this will irretrievably overwrite whatever opacity
> ```

BTW. The period should be within the parentheses?



_Suggestion:_
```Markdown
at `"/path/to/my/geometry"`. (That means using the path `"/path"` could affect
many geometries.) However, this will irretrievably overwrite whatever opacity
```
___
*[`Readme.md` line 312 at r3](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-NdkodU14vKiU1vqKy_6:-NdkodU14vKiU1vqKy_7:bb7lc56) ([raw file](https://github.com/meshcat-dev/meshcat/blob/77c5153e8ace0a7f28dce91c8a22ffc3e6a65c2b/Readme.md#L312)):*
> ```Markdown
> 
> Meshcat offers a pseudo property "modulated_opacity". By setting this value,
> meshcat remembers an objects inherent opacity and sets the rendered opacity to
> ```

nit.



_Suggestion:_
```Markdown
object's
```
___
*[`Readme.md` line 325 at r3](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-NdkpAG7DBoUbZKirplg:-NdkpAG7DBoUbZKirplh:bb7lc56) ([raw file](https://github.com/meshcat-dev/meshcat/blob/77c5153e8ace0a7f28dce91c8a22ffc3e6a65c2b/Readme.md#L325)):*
> ```Markdown
> </pre>
> 
> Setting `"modulated_opacity"` to 1 will restored the geometry's original
> ```

nit.



_Suggestion:_
```Markdown
restore
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks for the editorial clean up.

> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-:-NdksZAaE5dEttqYkQye:bi7vthn)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/153)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @zachfang)

___
*[`test/opacity.html` line 52 at r1](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-NdkafAiAQjrj07AIkWC:-Ndl0n1N54CyodGz0amB:b-rj0viw) ([raw file](https://github.com/meshcat-dev/meshcat/blob/0e30a85f5a9763ecd75a6c87bc094b45b159d8c4/test/opacity.html#L52)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The embedded data thing seems to be a common practice in these files. The nice thing is that its origin is not too important. I could actually take this string, paste it into a file `foo.gltf` and immediately load that file into any glTF viewer. There are other files that have stl, dae, obj files (and I've added files that also include base64-encoded images as background images). None of them are documented as to how they were authored. That includes the ability to create `foo.gltf`, pull it into the editor of your choice (e.g., Blender), edit it, export it again, and drop that text over this text to change the test.

And, finally, in this special case, it's actually self documented as having been created by Blender as part of the json.  :)
</blockquote></details>

OK Ah, missed that hehe

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/153)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI and @zachfang)

___
*[`test/opacity.html` line 52 at r1](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-NdkafAiAQjrj07AIkWC:-NdlQgXs-_kzyYJkGcGq:b-hxubj6) ([raw file](https://github.com/meshcat-dev/meshcat/blob/0e30a85f5a9763ecd75a6c87bc094b45b159d8c4/test/opacity.html#L52)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Ah, missed that hehe
</blockquote></details>

You wouldn't. It's a big soup of letters. If you don't know to look for it, you wouldn't bother.  :)

**Review by SeanCurtis-TRI — COMMENTED** [review]
BTW @zachfang and @EricCousineau-TRI 

If you look at the Reviewable status, it's complaining that only "2 of 4 files" have been reviewed and states that it's waiting on both of you. While I'm hard pressed to map that to exact actions, I'm currently interpreting such that I *believe* that if both of you click the eyball on the most current versions of all the files, we should be good.

> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-:-NdlQnp4-lkBWkP7KrNs:b808xv1)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI and @zachfang)

**Review by zachfang — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/153)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks, @zachfang. That seems to have been enough.

> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/153#-:-NdlaIavA2nV0e4dSkJB:b-vw4s4z)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SeanCurtis-TRI)

**Pull request merged**
