### PR TITLE
Fix KTX2 loader delegation to top-level default loader

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
If the user has amended the default loader, we should respect that when loading textures. Ditto for DRACO mesh geometry.

Twin PR: https://github.com/RobotLocomotion/drake/pull/21313

- - -
This change is [Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/179)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/179)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — APPROVED** [review]
:lgtm:, with my limited understanding of javascript.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/179#-:-Nvc34cw8hw7ay4jR0pn:bydmynt)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/179)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — APPROVED** [review]
:LGTM:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/179#-:-Nvc4ap059Za17VI-JiU:bmxilld)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Pull request merged**
