### PR TITLE
Add glTF support for DRACOLoader and KTX2Loader

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This increases the JS bundle size from 0.93 MiB to ~2.67 MiB~ _2.03 MiB_.

---

My current recipe for making optimized meshes:

```
$ docker run -it node:20.11.0 /bin/bash
# wget https://github.com/KhronosGroup/KTX-Software/releases/download/v4.3.1/KTX-Software-4.3.1-Linux-x86_64.deb
# dpkg -i KTX-Software-4.3.1-Linux-x86_64.deb 
# npm install --global @gltf-transform/cli
# gltf-transform optimize --compress draco --texture-compress ktx2 input.gltf output.gltf
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`src/index.js` line 27 at r1](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-NqOpAIN8E8qI0LlIhOx:-NqOpAIN8E8qI0LlIhOy:baqxq3) ([raw file](https://github.com/meshcat-dev/meshcat/blob/9aeecabcc457ba104ab841806bb297b162a89591/src/index.js#L27)):*
> ```JavaScript
>         import.meta.url).href,
>     'draco_decoder.js': new URL(
>         'three/examples/jsm/libs/draco/gltf/draco_decoder.js',
> ```

Working

This is only used for browsers that don't support WASM.
Maybe it's better to save space not support DRACO loading in that case.
___
*[`src/index.js` line 1109 at r1](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-NqOX7Tf10q9YFlrWrAM:-NqOX7Tg429a3WUyDgUe:by3bvjg) ([raw file](https://github.com/meshcat-dev/meshcat/blob/9aeecabcc457ba104ab841806bb297b162a89591/src/index.js#L1109)):*
> ```JavaScript
>         this.draco_loader = new DRACOLoader(meshcat_loading_manager);
>         this.ktx2_loader = new KTX2Loader(meshcat_loading_manager);
>         this.ktx2_loader.detectSupport(this.renderer);
> ```

At the moment, I'm doing the initialization once during the Viewer constructor.  I'm not sure if this has any cost/performance/compatibility downside?  It seems OK to far in local testing.

The other alternative would be to latch-init these the first time a glTF is loaded.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`src/index.js` line 27 at r1](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-NqOpAIN8E8qI0LlIhOx:-NqOrTz-4qdKcQqHVx_o:b-td71iv) ([raw file](https://github.com/meshcat-dev/meshcat/blob/9aeecabcc457ba104ab841806bb297b162a89591/src/index.js#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

This is only used for browsers that don't support WASM.
Maybe it's better to save space not support DRACO loading in that case.
</blockquote></details>

OK confirmed we don't need it.  Removed.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176)* status: 0 of 3 files reviewed, 2 unresolved discussions

___
*[`webpack.config.js` line 25 at r2](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-NqTVz8z5IERNtgH4nK5:-NqTVz8z5IERNtgH4nK6:b-1wz4rv) ([raw file](https://github.com/meshcat-dev/meshcat/blob/1d9f3d715c0463b0bd4ce2ffd0062d6160183ae7/webpack.config.js#L25)):*
> ```JavaScript
>         {
>           test: /\/libs\/(basis|draco)\//,
>           type: 'asset/inline'
> ```

Here, I'm bundling the `*.wasm` support files for DRACO and KTX2 into the same big `meshcat/dist/main.min.js` file as everything else in MeshCat.  That seems like the right trade-off to me.

The other alternative would be to add ~6 more files under `meshcat/dist/...`, and to tell the MeshCat code to wait to load those files until the first time they are needed.  Downstream applications that never planned to use glTF could ignore them.  Downstream applications wanted good glTF support would need to sync & serve the separate file of files as part of their server software.

The extra bloat we're talking is moving from to approx 1 MiB of JS (on master) to 2 MiB of JS (in this PR).  That still seems plenty small enough that the simplicity upside from the "monolithic single file" approach still wins out.

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI I'd appreciate your thoughts on the two open design questions posted in Reviewable.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-:-NqTha4RCeoOoYsYc5xI:bmxilld)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

___
*[`webpack.config.js` line 25 at r2](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-NqTVz8z5IERNtgH4nK5:-NqTgqeiCYFZeujYnfCr:bngfvkx) ([raw file](https://github.com/meshcat-dev/meshcat/blob/1d9f3d715c0463b0bd4ce2ffd0062d6160183ae7/webpack.config.js#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Here, I'm bundling the `*.wasm` support files for DRACO and KTX2 into the same big `meshcat/dist/main.min.js` file as everything else in MeshCat.  That seems like the right trade-off to me.

The other alternative would be to add ~6 more files under `meshcat/dist/...`, and to tell the MeshCat code to wait to load those files until the first time they are needed.  Downstream applications that never planned to use glTF could ignore them.  Downstream applications wanted good glTF support would need to sync & serve the separate file of files as part of their server software.

The extra bloat we're talking is moving from to approx 1 MiB of JS (on master) to 2 MiB of JS (in this PR).  That still seems plenty small enough that the simplicity upside from the "monolithic single file" approach still wins out.
</blockquote></details>

I agree. This path feels empowering for current workflows and an acceptable cost.  I think we'd have to have demonstrable harm to justify the extra complexity (and the implication of passing on that complexity to anyone who wants to write a server).
___
*[`src/index.js` line 1109 at r1](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-NqOX7Tf10q9YFlrWrAM:-NqThFpi2uDn_FrXGBCz:b9j9n43) ([raw file](https://github.com/meshcat-dev/meshcat/blob/9aeecabcc457ba104ab841806bb297b162a89591/src/index.js#L1109)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

At the moment, I'm doing the initialization once during the Viewer constructor.  I'm not sure if this has any cost/performance/compatibility downside?  It seems OK to far in local testing.

The other alternative would be to latch-init these the first time a glTF is loaded.
</blockquote></details>

Looks good to me.

**Comment by jwnimmer-tri** [comment]
My plan is to come up with a new `test/*.html` file before we merge this.  (I expect it to be pretty easy.)  The plan will be to have `python3 -m httpserver` in the loop to serve the unbundled files.

**Review by SeanCurtis-TRI — APPROVED** [review]
Probably clean up some unfortunate artifacts (copied from the source)?

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-:-NqUHkCe3YopzRDsrTcA:bhik2n6)* status: all files reviewed, 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`test/meshfile_object_gltf_optimized.html` line 294 at r4](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-NqUHE3l083ZRNG8jIhm:-NqUHE3l083ZRNG8jIhn:b2187a2) ([raw file](https://github.com/meshcat-dev/meshcat/blob/1ff91668f1a847bc61acacd8b39b472646381ec0/test/meshfile_object_gltf_optimized.html#L294)):*
> ```HTML
> 		// Using ["Background"] will also work for legacy reasons, but it will
> 		// lead to warnings generated in the browser's console.
> 		viewer.set_property(["Background"], "top_color", [1, 0.25, 0.25]);
> ```

nit As long as we're here, shall we ditch the comment and change the invocation so that this test doesn't spew this particular deprecation warning?



_Suggestion:_
```HTML
["Background", "<object>"]
```
___
*[`test/meshfile_object_gltf_optimized.html` line 296 at r4](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-NqUHRc783loPu0KDY-g:-NqUHRc783loPu0KDY-h:bcnh1s1) ([raw file](https://github.com/meshcat-dev/meshcat/blob/1ff91668f1a847bc61acacd8b39b472646381ec0/test/meshfile_object_gltf_optimized.html#L296)):*
> ```HTML
> 		viewer.set_property(["Background"], "top_color", [1, 0.25, 0.25]);
> 		viewer.set_property(["Background", "<object>"], "bottom_color", [0.25, 0.25, 1.0]);
> 		// Meaninglessly toggle background on and off to show that it doesn't
> ```

nit: These two commands are likewise unnecessary in this test. All of the background-related stuff should be in the `background.html` test file.

**Review by SeanCurtis-TRI — APPROVED** [review]
+@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-:-NqUHqr16D7hYsLSBndY:b-syrr9x)* status: all files reviewed, 2 unresolved discussions (waiting on @jwnimmer-tri and @rpoyner-tri)

**Review by SeanCurtis-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176)* status: all files reviewed, 3 unresolved discussions (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`test/meshfile_object_gltf_optimized.html` line 11 at r4](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-NqUHx4c1I4RTbBYTmgG:-NqUHx4c1I4RTbBYTmgH:b7v17ui) ([raw file](https://github.com/meshcat-dev/meshcat/blob/1ff91668f1a847bc61acacd8b39b472646381ec0/test/meshfile_object_gltf_optimized.html#L11)):*
> ```HTML
>         </div>
> 
>

**Comment by SeanCurtis-TRI** [comment]
*[`test/meshfile_object_gltf_optimized.html` line 11 at r4](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-NqUHx4c1I4RTbBYTmgG:-NqUI6JF7T8kxFXZsFWh:bgm3rv4) ([raw file](https://github.com/meshcat-dev/meshcat/blob/1ff91668f1a847bc61acacd8b39b472646381ec0/test/meshfile_object_gltf_optimized.html#L11)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Can we think up a click javascrpt mechanism to recognize whether or not the user has loaded this page the right way an provide in-browser correction?
</blockquote></details>

s/click/slick

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[`test/meshfile_object_gltf_optimized.html` line 11 at r4](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-NqUHx4c1I4RTbBYTmgG:-NqUPgooBy_qabmE6Pkq:bqqotsq) ([raw file](https://github.com/meshcat-dev/meshcat/blob/1ff91668f1a847bc61acacd8b39b472646381ec0/test/meshfile_object_gltf_optimized.html#L11)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

s/click/slick
</blockquote></details>

Is should be possible, but IMO not worth it.  The message already in the F12 console log when using `file://` URL seemed OK to me.

If we want to do anything, I think my advice would be to require that _all_ tests be run from an http server, so nobody tries files in the first place.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rpoyner-tri)

**Review by SeanCurtis-TRI — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rpoyner-tri)

___
*[`test/meshfile_object_gltf_optimized.html` line 11 at r4](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-NqUHx4c1I4RTbBYTmgG:-NqUUozD6M3JaToXKF_0:b1aet9v) ([raw file](https://github.com/meshcat-dev/meshcat/blob/1ff91668f1a847bc61acacd8b39b472646381ec0/test/meshfile_object_gltf_optimized.html#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Is should be possible, but IMO not worth it.  The message already in the F12 console log when using `file://` URL seemed OK to me.

If we want to do anything, I think my advice would be to require that _all_ tests be run from an http server, so nobody tries files in the first place.
</blockquote></details>

How obvious the error is is up for debate. But I like the resolution: homogenize on something more general.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rpoyner-tri)

**Review by rpoyner-tri — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, 2 of 3 files at r3, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-:-NqYd4x_0YRJfYhp24b5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`test/meshfile_object_gltf_optimized.html` line 270 at r6](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-NqYcwiv5wRrOtzN3QrW:-NqYcwiv5wRrOtzN3QrX:btp16af) ([raw file](https://github.com/meshcat-dev/meshcat/blob/a126435e3f53bf225aea69f94775873403257878/test/meshfile_object_gltf_optimized.html#L270)):*
> ```HTML
>             }
>         });
> 		// Enable shadows so we can see the meshes in the gltf cast and receive
> ```

nit o rama: are we sad about embedded literal tabs here?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

___
*[`test/meshfile_object_gltf_optimized.html` line 270 at r6](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-NqYcwiv5wRrOtzN3QrW:-NqYdc2ZDxZV2LYP-5IF:bvrzh2f) ([raw file](https://github.com/meshcat-dev/meshcat/blob/a126435e3f53bf225aea69f94775873403257878/test/meshfile_object_gltf_optimized.html#L270)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit o rama: are we sad about embedded literal tabs here?
</blockquote></details>

The current test corpus (of other files in this directory) is consistently inconsistent on this front.  To date, we've decided not to care.  Maybe someday we'll add a linter.

**Review by rpoyner-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — APPROVED** [review]
Looked and pleased.

> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/176#-:-NqYjCLm5wvV6YrfvzkR:bal1rei)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Pull request merged**
