### PR TITLE
Upgrade all dependencies to latest

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #142.
Closes #140.
Closes #133.

- - -
This change is [Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/165)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/165)* status: 0 of 5 files reviewed, all discussions resolved

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

I've done `meshcat_manual_test`, but I haven't run any of the `test/*.html` files yet.  I guess I'll try that now.

**Comment by jwnimmer-tri** [comment]
I guess it all looks OK to me.  In `meshfile_geometry_dae.html` I'm getting a console warning about `ColladaLoader`, but I get the same warning on master.

**Review by SeanCurtis-TRI — APPROVED** [review]
:LGTM:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/165#-:-Nor9o7783hXKbxpAJry:bmxilld)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by SeanCurtis-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/165)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ggould-tri)

**Review by ggould-tri — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/165#-:-NorNESW0aLSOk642PrY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/meshcat-dev/meshcat/165#-NorMn0W1bGsOdrk9fh3:-NorMn0W1bGsOdrk9fh4:b3e8am) (no related file):*
minor:  Some of the repository changes in `dist/main.min.js.THIRD_PARTY_LICENSES.json` don't look related to this PR.  I assume that it's a generated file?  If so, we should probably exclude it from review.
(it is currently minimized in reviewable as "likely minified", which is incorrect, but possibly it should be minimized for other reasons)

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/165)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/meshcat-dev/meshcat/165#-NorMn0W1bGsOdrk9fh3:-NorPKvG7VlC1M-aDI6S:b-id7wxd) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Some of the repository changes in `dist/main.min.js.THIRD_PARTY_LICENSES.json` don't look related to this PR.  I assume that it's a generated file?  If so, we should probably exclude it from review.
(it is currently minimized in reviewable as "likely minified", which is incorrect, but possibly it should be minimized for other reasons)
</blockquote></details>

It's actually important to review the contents of that file, to ensure that no unacceptable licenses have snuck in.  I'll see what I can do to convince reviewable about that, separately.

___

**Review by SeanCurtis-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/meshcat-dev/meshcat/165)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Pull request merged**
